### ISSUE TITLE
Vector does not work with 3.11.8-1

### ISSUE THREAD

**Issue by lzap** [Netflix/vector#172]
Hello, I installed PCP 3.11.8-1 from CentOS 7.4 and downloaded Vector 1.1.0, unpacked and started pcp-webd but in the UI I am getting this error when I attempt to enter hostname of my host (localhost shows nothing there):

    vendor.js:21994 Error: Failed to execute 'open' on 'XMLHttpRequest': Invalid URL

Nothing in particular with "-v" flag there:

```
[Mon Oct 30 09:01:18] pmwebd(22452): pmwebd
        Started daemon on IPv4 TCP port 44323
        Started daemon on IPv6 TCP port 44323
        Verbosity level 1
        Permissive mode disabled
        Using libmicrohttpd 0.9.33
        PMAPI prefix /pmapi
        Serving non-pmwebapi URLs under directory /usr/share/pcp/webapps
        Remote context creation requests enabled
        Archive base directory: /var/log/pcp
        Graphite API enabled
        Graphite API name encoding short
        Graphite API Cairo graphics rendering compiled-in
        HTTP compression compiled-in
        Periodic client statistics dumped roughly every 300s
        Using up to 4 auxiliary threads
[Mon Oct 30 09:01:20] pmwebd(22452): [178.77.243.253:41566] HTTP/1.1 GET /index.html
```

I tried with both vector 1.1.0 "vanilla" and with `pcp-webapp-vector` package from RHEL 7.4.

**Comment by lzap** [comment]
Hey @natoscott is it possible that there was a regression in the web API in RHEL 7.4? It used to work when I tried this during the summer.

**Comment by natoscott** [comment]
@lzap not that I'm aware of.  vector-1.1.0 is working fine for me with just released pcp-3.12.2 too FWIW.

**Comment by lzap** [comment]
My bad, I was entering the hostname into hostspec. I am no UX expert, but the dropdown (plus) seemed like empty container. Sorry for the noise.

**Comment by fche** [comment]
The top level index.html file that comes with the bundled pcp webapps includes a startup link into vector that fills in a valid hostname/hostspec.  A snippet of javascript adds the appropriate `#?host=HOSTNAME` querystring to the URL.

**Comment by lzap** [comment]
Thanks. I always have localhost there, which does not work.

**Comment by 001101** [comment]
same here

**Comment by lzap** [comment]
You need to enter hostname into proper UI field, it's little bit confusing UI for me.

**Comment by spiermar** [comment]
@lzap any suggestions on how to make it a bit more easy?

**Comment by lzap** [comment]
No idea, sorry. This works for me, I am casual Vector user.

**Comment by spiermar** [comment]
Trying to figure out if there are better ways to structure the UI. The pair hostname/hostspec makes sense if know PCP well, but maybe not to others. ;-)

**Comment by fche** [comment]
Consider making the 'hostspec' (target context host) part the primary visible text field in the UI, naturally defaulting to 'localhost', but putting emphasis on the resulting pmcd.hostname text.  The 'hostname' (pmwebd relay) could be inferred by default from the web page's document.url by heuristic.  (add port :44323 etc.); make it overrideable via popup or something non-emphasized.
